title: <h1>Said Allaz</h1>
#picture: /assets/me.jpg
#logo: /assets/me.jpg
description: the following portfolio is a brief description for some of my previous experinces
#show_downloads: true
#google_analytics: true
theme: jekyll-theme-leap-day
